create table wallet (user_id varchar(255) not null, primary key (user_id));
create table wallet_entries (wallet_user_id varchar(255) not null, entries_id bigint not null);
create table wallet_entry (id bigint generated by default as identity, amount double not null, currency varchar(255), primary key (id));

alter table wallet_entries add constraint UK_ifem0a4f3fhlwu1il854eaxot unique (entries_id);
alter table wallet_entries add constraint FKbqwgqo6ndojqed20v2aje0i9n foreign key (entries_id) references wallet_entry;
alter table wallet_entries add constraint FKmi0b29x4imyldu3eaji4l6pxc foreign key (wallet_user_id) references wallet;

insert into wallet values ('Daniel');
insert into wallet values ('Adib');
insert into wallet values ('Madhura');

insert into wallet_entry values (null, 10, 'BTC');
insert into wallet_entry values (null, 100, 'BCH');
insert into wallet_entries values ('Daniel', 1);
insert into wallet_entries values ('Daniel', 2);

insert into wallet_entry values (null, 50, 'BTC');
insert into wallet_entry values (null, 340, 'BCH');
insert into wallet_entries values ('Adib', 3);
insert into wallet_entries values ('Adib', 4);

insert into wallet_entry values (null, 80, 'BTC');
insert into wallet_entry values (null, 120, 'LTC');
insert into wallet_entries values ('Madhura', 5);
insert into wallet_entries values ('Madhura', 6);